Revert "src/ceph-crash.in: remove unused frame in handler()"
This reverts commit 0b85a0b16ce09ae547c5c87bea34802883ab4bd0.

unused but required:

```
Traceback (most recent call last):
File "/usr/bin/ceph-crash", line 102, in <module>
main()
File "/usr/bin/ceph-crash", line 98, in main
time.sleep(args.delay * 60)
TypeError: handler() takes exactly 1 argument (2 given)
```

Fixes: https://tracker.ceph.com/issues/54422

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>