crimson/osd: fix FTBFS due to smart-ptr-to-bool conversion in fmt::ptr
```
../src/fmt/include/fmt/format.h: In instantiation of ‘const void* fmt::v9::ptr(T) [with T = seastar::shared_ptr<crimson::net::SocketConnection>]’:
../src/crimson/net/ProtocolV2.cc:1109:72:   required from here
../src/fmt/include/fmt/format.h:3809:37: error: static assertion failed
 3809 |   static_assert(std::is_pointer<T>::value, "");
      |                                     ^~~~~
../src/fmt/include/fmt/format.h:3809:37: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
```

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>