ceph.spec.in: add man/rgw-gap-list
Introduced in https://github.com/ceph/ceph/pull/62749
Centos builds fail with:
```
error: Installed (but unpackaged) file(s) found:
   /usr/share/man/man8/rgw-gap-list.8.gz

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/share/man/man8/rgw-gap-list.8.gz
```

Signed-off-by: Matan Breizman <mbreizma@redhat.com>