doc/cephadm: Remove shell alias
Turns out, the alias doesn't work for files.

Fixes: https://tracker.ceph.com/issues/46701

Fixes:

```
$ ceph orch apply -i myfile.yaml
ERROR: no such file or directory: myfile.yaml
```

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
Signed-off-by: Zac Dover <zac.dover@gmail.com>