rpm: add missing % in %dir directive
05f9218fea5d776d4480e693ae5b6115e36e2810 added an explicit %dir directive for
a new directory added to the ceph-common package, but -- due to a typo --
neglected to include the "%". As a result, RPM builds started to fail with:

Processing files: ceph-common-17.0.0-2787.gde6c8250.el8.x86_64
error: File must begin with "/": {_libdir}/ceph/denc/

RPM build errors:
    File must begin with "/": {_libdir}/ceph/denc/

Fixes: 05f9218fea5d776d4480e693ae5b6115e36e2810
Signed-off-by: Nathan Cutler <ncutler@suse.com>