src/CMakeLists.txt: add -Wno-vla-cxx-extension to clang
The following warning of:
```
error: variable length arrays in C++ are a Clang extension
[-Werror,-Wvla-cxx-extension]
```
is enabled by default in clang 18 and above.
Disable it in our builds due to large anmount of warnings.
We can revert this once we handle some of the warnings in future PRs.

Signed-off-by: Matan Breizman <mbreizma@redhat.com>