Revert "Merge pull request #8346 from yuyuyu101/wip-async-clock"
This reverts commit ff71ac68865f593e893103e4d38b61047628075a, reversing
changes made to 8c4bf3119798af20fd04e65dfae524516d764503.

This broke the build:

msg/async/Event.cc: In member function 'int EventCenter::process_time_events()':
error: msg/async/Event.cc:280:30: cannot bind 'std::basic_ostream' lvalue to 'std::basic_ostream&&'
ldout(cct, 10) << __func__ << " cur time is " << now << dendl;
^

and elsewhere...

Signed-off-by: Sage Weil <sage@redhat.com>