test: allow ceph_kvstorebench to be build on FreeBSD
Add compat.h to fix missing error codes
```
/home/srcs/Ceph/bluestore/ceph/src/key_value_store/kv_flat_btree_async.cc:448:15: error: use of undeclared identifier 'EUCLEAN'
      return -EUCLEAN;
              ^
/home/srcs/Ceph/bluestore/ceph/src/key_value_store/kv_flat_btree_async.cc:1434:11: error: use of undeclared identifier 'EKEYREJECTED'
    case -EKEYREJECTED: {
          ^
/home/srcs/Ceph/bluestore/ceph/src/key_value_store/kv_flat_btree_async.cc:1554:11: error: use of undeclared identifier 'EKEYREJECTED'
    case -EKEYREJECTED: {
          ^
/home/srcs/Ceph/bluestore/ceph/src/key_value_store/kv_flat_btree_async.cc:1583:17: error: use of undeclared identifier 'EUCLEAN'
          case -EUCLEAN:
                ^
/home/srcs/Ceph/bluestore/ceph/src/key_value_store/kv_flat_btree_async.cc:1661:18: error: use of undeclared identifier 'EUCLEAN'
      && err != -EUCLEAN){
                 ^
```

Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>