common: include <signal.h> in Preforker.h
Since it does use functions declared by signal.h

/home/jenkins/workspace/ceph-master/src/common/Preforker.h:50:5: error: use of undeclared identifier                                             'sigemptyset'
    sigemptyset(&sa.sa_mask);
    ^
/home/jenkins/workspace/ceph-master/src/common/Preforker.h:52:9: error: no matching constructor for                                             initialization of 'sigaction'
    if (sigaction(SIGHUP, &sa, nullptr) != 0) {
        ^         ~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/signal.h:366:8: note: candidate constructor (the implicit copy constructor) not via                                            ble: requires 1 argument, but 3 were provided
struct sigaction {
       ^
/usr/include/sys/signal.h:366:8: note: candidate constructor (the implicit move constructor) not via                                            ble: requires 1 argument, but 3 were provided
/usr/include/sys/signal.h:366:8: note: candidate constructor (the implicit default constructor) not                                             viable: requires 0 arguments, but 3 were provided
2 errors generated.

fixes: https://github.com/ceph/ceph/pull/35844
Signed-off-by: Willem Jan Withagen <wjw@digiware.nl>