test/pybind/test_rados: always pass bytes to rados.Object.set_xattr()
> an empty '' is of type str, not bytes.

python3 says. so let's be more explicit.

this change address failures like:
```
======================================================================
ERROR: test_rados.TestIoctx.test_obj_xattrs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in
runTest
    self.test(*self.arg)
  File "/var/ssd/ceph/src/test/pybind/test_rados.py", line 380, in
test_obj_xattrs
    obj.set_xattr(key, value)
  File "rados.pyx", line 4119, in rados.set_object_locator.retfunc
  File "rados.pyx", line 4129, in rados.set_object_namespace.retfunc
  File "rados.pyx", line 4204, in rados.Object.set_xattr
  File "rados.pyx", line 572, in rados.requires.wrapper.validate_func
  File "rados.pyx", line 560, in rados.requires.check_type
TypeError: xattr_value must be bytes
```

Signed-off-by: Kefu Chai <kchai@redhat.com>