test/rgw/multisite: test error handling of forwarded iam:DeleteRole
DeleteRole's conflict handling happens after forwarding, so use
test_role_delete_sync() to test that forwarded 409 Conflict errors
preserve the DeleteConflict code and error message

without the fix to forward_iam_request_to_master(), DeleteRole instead
fails with:

> botocore.exceptions.ClientError: An error occurred (BucketNotEmpty) when calling the DeleteRole operation: None

Signed-off-by: Casey Bodley <cbodley@redhat.com>