crimson/tools: fix FTBFS due to seastore/segment_cleaner.h
```
In file included from ../src/crimson/tools/store_nbd/tm_driver.cc:4:
../src/crimson/tools/store_nbd/tm_driver.h:7:10: fatal error: crimson/os/seastore/segment_cleaner.h: No such file or directory
    7 | #include "crimson/os/seastore/segment_cleaner.h"
      |
```

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>