common: missing std include with GCC 14
In file included from src/rgw/driver/posix/bucket_cache.h:19,
                 from src/test/rgw/test_posix_bucket_cache.cc:4:
src/common/cohort_lru.h: In member function _void cohort::lru::TreeX<T, TTree, CLT, CEQ, K, LK>::lock()_:
src/common/cohort_lru.h:334:14: error: _for_each_ is not a member of _std_
  334 |         std::for_each(locks.begin(), locks.end(),
      |              ^~~~~~~~
src/common/cohort_lru.h: In member function _void cohort::lru::TreeX<T, TTree, CLT, CEQ, K, LK>::unlock()_:
/home/yuvalif/ceph5/src/common/cohort_lru.h:339:14: error: _for_each_ is not a member of _std_
  339 |         std::for_each(locks.begin(), locks.end(),
      |              ^~~~~~~~

Signed-off-by: Yuval Lifshitz <ylifshit@ibm.com>