pybind: do not check MFLAGS
clang does not check for directories passed by -iquote/path/to/foo.h, if
a header is included using `#include <foo.h>`

it complains:

/home/kefu/ceph/src/pybind/rados/tmpwzjOsS/rados_dummy.c:2:10: error:
'rados/librados.h' file not found with <angled> include; use "quotes"
instead
         ^~~~~~~~~~~~~~~~~~
         "rados/librados.h"
1 error generated.

and MFLAGS does not exist in the env variables of setup.py launched by
the top-level make.

Signed-off-by: Kefu Chai <kchai@redhat.com>