node-proxy: fix a regression when processing the RedFish API
37dde2653b7 introduced a regression.

`Endpoint()` doesn't take a `EndpointMgr` object as parameter.
The call `e = Endpoint(self, _url, self.client)` obviously throws the
following error:

```
TypeError: __init__() takes 3 positional arguments but 4 were given
```

This commit fixes it.

Fixes: https://tracker.ceph.com/issues/68231

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>